module Page.Menu exposing (render)

import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (onClick)
import Types exposing (Model, Msg(NewUrl))


render : Model -> Html Msg
render model =
    nav [ class "navbar is-fixed-top", id "navbar" ]
        [ div [ class "bd-special-shadow", id "specialShadow", style [ ( "", "" ) ] ]
            []
        , div [ class "container" ]
            [ div [ class "navbar-brand" ]
                [ a [ class "navbar-item", href "/" ]
                    [ img [ alt "haskell.com.ua", attribute "height" "28", src "https://www.haskell.org/static/img/haskell-logo.svg" ]
                        []
                    ]
                , div [ class "navbar-burger burger", attribute "data-target" "navBarMenu" ]
                    [ span []
                        []
                    , span []
                        []
                    , span []
                        []
                    ]
                ]
            , div [ class "navbar-menu", id "navBarMenu" ]
                [ div [ class "navbar-start" ]
                    [ a [ class "navbar-item", onClick (NewUrl "/") ]
                        [ text "About" ]
                    , a [ class "navbar-item", href "https://www.haskell.org/news" ]
                        [ text "News" ]
                    , div [ class "navbar-item has-dropdown is-hoverable" ]
                        [ a [ class "navbar-link", href "#" ]
                            [ text "Downloads" ]
                        , div [ class "navbar-dropdown is-boxed" ]
                            [ a [ class "navbar-item", href "https://www.haskell.org/downloads/" ]
                                [ text "Haskell" ]
                            , hr [ class "navbar-divider" ]
                                []
                            , a [ class "navbar-item is-active", href "http://elm-lang.org/" ]
                                [ text "elm" ]
                            ]
                        ]
                    ]
                , div [ class "navbar-end" ]
                    [ div [ class "navbar-item" ]
                        [ p [ class "control" ]
                            [ a [ class "bd-envelope-button button", href "/instagram", target "_blank" ]
                                [ span [ class "icon" ]
                                    [ i [ class "fa fa-envelope" ]
                                        []
                                    ]
                                , a [ href "mailto:systemdef.com@gmail.com?subject=haskell.com.ua" ]
                                    [ text "Send email" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
